// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFerien(arg1:main.Ferien):Promise<main.Ferien>;

export function CreateMedikament(arg1:main.Medikament):Promise<main.Medikament>;

export function DeleteFerien(arg1:number):Promise<boolean>;

export function DeleteMedikament(arg1:number):Promise<boolean>;

export function GetFerien():Promise<Array<main.Ferien>>;

export function GetMedikamente():Promise<Array<main.Medikament>>;

export function GetWarnfrist():Promise<number>;

export function Quit():Promise<void>;

export function UpdateFerien(arg1:main.Ferien):Promise<main.Ferien>;

export function UpdateMedikament(arg1:main.Medikament):Promise<main.Medikament>;

export function UpdateWarnfrist(arg1:number):Promise<number>;
