// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFerien(arg1) {
  return window['go']['main']['App']['CreateFerien'](arg1);
}

export function CreateMedikament(arg1) {
  return window['go']['main']['App']['CreateMedikament'](arg1);
}

export function DeleteFerien(arg1) {
  return window['go']['main']['App']['DeleteFerien'](arg1);
}

export function DeleteMedikament(arg1) {
  return window['go']['main']['App']['DeleteMedikament'](arg1);
}

export function GetFerien() {
  return window['go']['main']['App']['GetFerien']();
}

export function GetMedikamente() {
  return window['go']['main']['App']['GetMedikamente']();
}

export function GetWarnfrist() {
  return window['go']['main']['App']['GetWarnfrist']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function UpdateFerien(arg1) {
  return window['go']['main']['App']['UpdateFerien'](arg1);
}

export function UpdateMedikament(arg1) {
  return window['go']['main']['App']['UpdateMedikament'](arg1);
}

export function UpdateWarnfrist(arg1) {
  return window['go']['main']['App']['UpdateWarnfrist'](arg1);
}
